# Workflow derived from
# https://github.com/tidyverse/dplyr/blob/master/.github/workflows/test-coverage.yaml
on:
  push:
    branches: [main, master]
    paths: [R/**, tests/**, DESCRIPTION]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        run: |
          Sys.setenv(NOT_CRAN = "true")
          covr::codecov(line_exclusions = c("R/shiny.R", "R/dashboard.R"), function_exclusions = "^plot_")
        shell: Rscript {0}
